#!/usr/bin/env python3
"""F4-0 — which CreatePolicy request shape, if any, accepts guardrails-in-policy syntax.

WHY THIS SCRIPT EXISTS
----------------------
The F4 smoke run (n=3, 2026-08-11) failed at its first control-plane call:

    CreatePolicy(guardrail) failed: ValidationException: When parsing the policy statement,
    the following errors occurred:
    * unexpected token `guardrails`

The statement sent was, verbatim, the syntax the document under test prescribes at L125
("Define guardrails inline within Cedar policies using `when guardrails { ... }`"), L322, L390,
L416, L792 and L879, generated by `lib/cedar.py`:

    forbid (principal, action, resource == AgentCore::Gateway::"<arn>")
    when guardrails {
        BedrockGuardrails::ContentFilter(["HATE"], [context.output.text])["HATE"]
            .confidenceScore.greaterThan(decimal("0.2"))
    };

That is a conflict candidate against the document. It is NOT YET a finding, because the
observation has at least four candidate explanations and only one of them is "the document is
wrong". The conflict-resolution protocol requires an alternative-explanation register BEFORE an
amendment, so this script enumerates the alternatives and measures them:

  H1  THE DOCUMENT IS WRONG about the syntax (or about it being available at all).
  H2  THE HARNESS SENT THE WRONG REQUEST SHAPE. `CreatePolicy.definition` at botocore 1.43.67
      is a union-like structure with THREE members — `cedar{statement}`, `policy{statement}`
      and `policyGeneration{...}`. Every script in this repo sends `cedar`. If the extended
      grammar is parsed only under `policy`, then `cedar` is the legacy plain-Cedar parser and
      "unexpected token `guardrails`" is exactly what a plain Cedar parser SHOULD say. This
      would make the failure an artefact of our own transcription, and F4-1 would be
      measurable after a one-line change.
  H3  THE SYNTAX IS RIGHT BUT THE SPELLING IS OURS. `lib/cedar.py` composes the block; the
      document shows `when guardrails { ... }` in prose but never a complete policy. The
      condition body, the `BedrockGuardrails::` namespace, the `[...]` path list, the
      `["HATE"]` re-index and `.confidenceScore.greaterThan(decimal("0.2"))` chain could each
      be wrong independently of the `when guardrails` keyword.
  H4  THE FEATURE IS NOT AVAILABLE ON THIS ENGINE/REGION/ACCOUNT. us-east-1 is on the verified
      guardrails-in-policy region list, but availability could be gated per policy engine or
      per account rather than per region.

`--dry-run` prints the matrix and makes no call.

WHAT THIS SCRIPT MEASURES
-------------------------
A full factorial over the two axes that H2 and H3 name:

    definition member  x  statement variant
    {cedar, policy}       {doc_syntax, plain_when, input_path, suppress_output,
                           plain_when_input, narrow_permit, no_condition}

The variant list grew across three rounds on 2026-08-11 and every addition is recorded rather
than folded in silently, because a matrix that grows to fit its results is only honest if the
growth is visible:

  round 1  {doc_syntax, plain_when, no_condition} — answered the request-shape question (the
           extended grammar is under `definition.policy`, not `definition.cedar`) and raised a
           data-path question it had no cell to answer.
  round 2  +input_path — showed `context.input.*` creates where `context.output.*` does not, in
           an authorization policy. Raised: is the document wrong about output filtering?
  round 3  +suppress_output (the document's own answer: L332 names a distinct effect for output
           filtering, so the harness was in error, and this cell tests that the named effect
           exists), +plain_when_input (round 2 could not reach L322's mixing claim because both
           `when` cells died on the data path first), +narrow_permit (F4-4's and F4-5's permit,
           which `definition.policy` may validate semantically where `definition.cedar` did not).

`no_condition` is the CONTROL, and it is what makes the other thirteen interpretable. It is a
`forbid` with no condition at all — grammar the service is already known to accept, since the
shared baseline permit was created through this same path. If `no_condition` fails under
`policy`, then `policy` is not a usable request shape at all and its guardrail results say
nothing about guardrail grammar. Without that control, a rejection under `policy` would be
ambiguous between "this member does not exist in practice" and "this grammar is wrong".

`plain_when` moves the identical condition body from `when guardrails {...}` into a standard
`when {...}`. It separates the KEYWORD from the BODY: if `plain_when` parses and `doc_syntax`
does not, the document's keyword is wrong and its condition is fine; if both fail with an error
naming a token inside the body, the body is wrong (H3) and the document's keyword has not been
tested yet.

ORACLE
------
There is no verdict here and no pre-registered n. This is INSTRUMENT CALIBRATION, not an
experiment, and it is labelled as such: it decides which request shape F4 must send, and it
writes an alternative-explanation register that a later F4 finding can cite. Calibration is
reported as a table of observations. Publishing it as a verdict would be claiming a result the
design cannot support — fourteen single trials, one per cell, of a deterministic control-plane
validator.

That determinism is why n=1 is defensible HERE and nowhere else in this project: a Cedar parse
either accepts a byte string or it does not. To keep that assumption falsifiable rather than
assumed, each cell is sent TWICE with different policy names, and disagreement between the two
is recorded as `stable: false` and makes the cell unusable.

COST AND BLAST RADIUS
---------------------
$0. Control-plane CreatePolicy/DeletePolicy only — no gateway request, no model, no guardrail
evaluation, no text units. At most 28 CreatePolicy calls at the self-imposed 5/s limit.

Every policy that IS created is created `enforcementMode=LOG_ONLY` and is deleted immediately,
in a `finally`, and is registered in `state.json` before its status is ever polled — `policy`
accepts no `tags` member, so the ledger is the only channel that can find a leaked one. A
created policy is scoped `resource == <main gateway arn>`, so even in the seconds it exists it
cannot reach the six pre-existing READY gateways.

Nothing here touches the shared baseline permit, either axis of the gateway, or the engine's
mode. The probe is additive: it creates and deletes its own policies and changes no existing
resource. Teardown re-runs infra/06_verify.py's own checks anyway, because "the probe changed
nothing" is a claim and not an assumption.
"""

from __future__ import annotations

import importlib.util
import json
import sys
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "lib"))

import awsclients as A                                                     # noqa: E402
import cedar                                                              # noqa: E402
import oracle as O                                                        # noqa: E402
import phase1 as P                                                        # noqa: E402
import testbed as T                                                       # noqa: E402
from evidence import EvidenceStore, capture                               # noqa: E402

VERIFY_MODULE_NAME = "grx_infra_06_verify_probe"
_spec_vf = importlib.util.spec_from_file_location(
    VERIFY_MODULE_NAME, ROOT / "infra" / "06_verify.py")
_vf = importlib.util.module_from_spec(_spec_vf)
sys.modules[VERIFY_MODULE_NAME] = _vf
_spec_vf.loader.exec_module(_vf)
Checks = _vf.Checks
verify_engine = _vf.verify_engine
verify_gateways = _vf.verify_gateways

FAMILY = "f4_modes"
CASE = "F4-0"

# The condition body, held in ONE place. Both the doc-syntax cell and the plain-when cell must
# send byte-identical bodies or the axis is confounded with the thing it is meant to isolate.
COND = cedar.guardrail_condition(
    "ContentFilter", ["HATE"], ["context.output.text"], threshold="0.2")

# Identical in every respect except the data path. See `statement_variants` for why this exists.
COND_INPUT = cedar.guardrail_condition(
    "ContentFilter", ["HATE"], ["context.input.text"], threshold="0.2")

DEFINITION_MEMBERS = ("cedar", "policy")

# CreatePolicy.name is capped at 48 characters by the service model and the run_id is 17 of them,
# so the cell identity has to fit in what is left. These abbreviations are only for the NAME; the
# full member and variant travel in the description, the ledger and calibration.json.
ABBREV = {"cedar": "c", "policy": "p",
          "doc_syntax": "doc", "plain_when": "pw", "input_path": "in", "no_condition": "ctl",
          "suppress_output": "so", "plain_when_input": "pwi", "narrow_permit": "np"}

REPEATS = 2      # see the ORACLE section: n=1 per cell, sent twice, to keep determinism testable

# DeletePolicy on a policy that has not settled returns ConflictException. Measured 2026-08-11:
# all four accepted cells took one GetPolicy to read ACTIVE and then deleted on attempt 1.
TERMINAL_FOR_DELETE = ("ACTIVE", "CREATE_FAILED", "UPDATE_FAILED", "DELETE_FAILED")
DELETE_STATUS_ATTEMPTS = 10
DELETE_STATUS_SLEEP_S = 3.0
DELETE_ATTEMPTS = 5
DELETE_SLEEP_S = 3.0


def _status_now(ac, *, engine_id: str, policy_id: str) -> str:
    """Raw GetPolicy for the delete-readiness poll only.

    Raw, not captured: a poll writes one evidence record per iteration and would bury the
    settled read that is the actual evidence. ResourceNotFound is "GONE", not an error — a
    policy that never became visible cannot be leaked.
    """
    try:
        return ac.get_policy(policyEngineId=engine_id, policyId=policy_id).get("status", "")
    except Exception as exc:                                               # noqa: BLE001
        if type(exc).__name__ == "ResourceNotFoundException":
            return "GONE"
        return f"POLL_ERROR:{type(exc).__name__}"


def statement_variants(gateway_arn: str) -> dict[str, dict[str, str]]:
    """The four statement variants, each with the hypothesis it discriminates.

    `input_path` was added after round 1 (2026-08-11) and the addition is recorded rather than
    silently folded in. Round 1's `definition.policy` column rejected both guardrail cells with a
    SEMANTIC error, not a grammar one:

        Guardrail 'BedrockGuardrails::ContentFilter' references 'context.output' but the policy
        has an authorization effect. Use 'context.input.*' data paths for authorization policies.

    That answered the question the matrix was built to answer (the extended grammar lives under
    `definition.policy`, not `definition.cedar`) and immediately raised one it could not: is the
    rejection about the PATH or about guardrails-in-authorization-policies as such? Round 1 has
    no cell that varies the path, so it cannot distinguish them, and F4-1 needs the answer —
    without a creatable guardrail policy F4-1 has no treatment condition at all.

    `input_path` is byte-identical to `doc_syntax` except for `context.output.text` ->
    `context.input.text`. One factor, one difference.
    """
    res = cedar.gateway_resource(gateway_arn)
    if "AgentCore::Gateway::" not in res:
        raise RuntimeError(
            "cedar.gateway_resource fell back to the unscoped `resource is AgentCore::Gateway`, "
            "which would scope a forbid to EVERY gateway in the account including the six "
            "pre-existing READY ones. Refusing to send it")
    return {
        "doc_syntax": {
            "statement": cedar.statement("forbid", resource=res, when_guardrails=COND),
            "tests": "H1/H3 — the document's own `when guardrails { ... }` keyword, L125/L322",
        },
        "plain_when": {
            # Composed by hand, NOT via cedar.statement(when=...): lib/cedar.py deliberately
            # raises when a guardrail function appears in a standard `when`, which is itself an
            # encoding of the document's L322 claim. Bypassing that guard is the point of this
            # cell — the guard's premise is exactly what is in question.
            "statement": (f"forbid (principal, action, resource == {res.split(' == ')[1]})\n"
                          f"when {{\n    {COND}\n}};"),
            "tests": ("H3 — identical condition body under a STANDARD `when`. Separates the "
                      "keyword from the body, and tests L322's claim that the two cannot mix"),
        },
        "input_path": {
            "statement": cedar.statement("forbid", resource=res, when_guardrails=COND_INPUT),
            "tests": ("added in round 2 — byte-identical to doc_syntax except "
                      "context.output.text -> context.input.text. Discriminates 'the PATH is "
                      "rejected' from 'guardrails in an authorization policy are rejected'. "
                      "F4-1 has no treatment condition unless one of these two forms creates"),
        },
        "suppress_output": {
            "statement": cedar.statement("suppressOutput", resource=res, when_guardrails=COND),
            "tests": ("added in round 3 — the document's own resolution of round 2. L332 and "
                      "L392 say output filtering uses the `suppressOutput` effect, a DISTINCT "
                      "effect from permit/forbid, so the service's 'the policy has an "
                      "authorization effect' is consistent with the document and the harness "
                      "was the thing in error. This cell tests whether the effect the document "
                      "names actually exists and accepts the output path"),
        },
        "plain_when_input": {
            # Hand-composed for the same reason as `plain_when`.
            "statement": (f"forbid (principal, action, resource == {res.split(' == ')[1]})\n"
                          f"when {{\n    {COND_INPUT}\n}};"),
            "tests": ("added in round 3 — a guardrail function in a STANDARD `when` with an "
                      "accepted data path. Round 2 could not test L322's claim (2) that you "
                      "cannot mix standard Cedar `when {...}` with `when guardrails {...}`, "
                      "because both `when` cells were rejected on the data path first. If this "
                      "is ACCEPTED, L322 (2) is at least imprecise: the guardrails block is not "
                      "required to host a guardrail function"),
        },
        "narrow_permit": {
            "statement": cedar.statement(
                "permit", resource=res, when="context.input.amount < 500"),
            "tests": ("added in round 3 — F4-4's narrow permit. No `context.` path appears "
                      "anywhere in the document under test; the shape comes from lib/cedar.py's "
                      "own samples, and `definition.policy` has now been shown to validate data "
                      "paths semantically rather than pass them through. If this is rejected, "
                      "F4-4 and F4-5 have no permit to test with"),
        },
        "no_condition": {
            "statement": cedar.statement("forbid", resource=res),
            "tests": ("CONTROL — grammar already known to be accepted (the shared baseline "
                      "permit came through this path). If this fails, the request SHAPE is "
                      "broken and nothing else in that column is interpretable"),
        },
    }


def _probe(ac, store: EvidenceStore, state: T.State, *, engine_id: str, member: str,
           variant: str, statement: str, run_id: str, rep: int) -> dict[str, Any]:
    """One CreatePolicy attempt. Records the outcome; deletes anything it created."""
    # Abbreviated because CreatePolicy.name caps at 48 characters and the run_id alone is 17.
    # T.check_name enforces that cap offline from the service model, which is why this cost a
    # ValueError rather than a live ValidationException.
    name = T.check_name(ac, "CreatePolicy",
                        f"grx_f4p_{ABBREV[member]}_{ABBREV[variant]}_{rep}_{run_id}")
    out: dict[str, Any] = {"member": member, "variant": variant, "rep": rep, "name": name,
                           "statement": statement}
    A.limiter().wait("CreatePolicy")
    rec = capture(store, "create_policy", ac,
                  name=name, policyEngineId=engine_id,
                  definition={member: {"statement": statement}},
                  description=f"F4-0 syntax probe: definition.{member} x {variant}",
                  validationMode="IGNORE_ALL_FINDINGS",
                  enforcementMode="LOG_ONLY")
    out["accepted"] = bool(rec.ok)
    out["request_id"] = rec.request_id
    out["error_code"] = rec.error_code
    out["error_message"] = rec.error_message
    out["policy_id"] = (rec.response or {}).get("policyId", "") if rec.ok else ""

    if out["policy_id"]:
        state.record(T.Resource(
            kind="policy", logical=f"f4probe_{member}_{variant}_{rep}", name=name,
            service="bedrock-agentcore-control", delete_op="delete_policy",
            delete_params={"policyEngineId": engine_id, "policyId": out["policy_id"]},
            ids={"policy_id": out["policy_id"], "policy_engine_id": engine_id},
            delete_priority=40,
            notes="F4-0 syntax probe; deleted in the same run. `policy` takes no tags, so this "
                  "ledger entry is the only thing that can find it if the run dies"))
        # A policy cannot be deleted until it reaches a terminal state: the first version of this
        # script called DeletePolicy immediately and got ConflictException on all four accepted
        # cells, leaving them live on the SHARED engine. They were LOG_ONLY and scoped to our own
        # gateway so they enforced nothing, but "harmless" is not "absent" — `_apply_config`
        # refuses any cell that does not declare a mode for every policy on the engine, so four
        # undeclared policies would have blocked F4 rather than silently biasing it. Poll first,
        # then delete, then retry: three separate reasons, none of which is optional.
        out["status_waits"] = []
        for attempt in range(1, DELETE_STATUS_ATTEMPTS + 1):
            st = _status_now(ac, engine_id=engine_id, policy_id=out["policy_id"])
            out["status_waits"].append(st)
            if st in TERMINAL_FOR_DELETE:
                break
            time.sleep(DELETE_STATUS_SLEEP_S)
        out["status_at_delete"] = out["status_waits"][-1] if out["status_waits"] else ""

        out["deleted"] = False
        out["delete_error"] = ""
        out["delete_attempts"] = 0
        for attempt in range(1, DELETE_ATTEMPTS + 1):
            A.limiter().wait("DeletePolicy")
            drec = capture(store, "delete_policy", ac,
                           policyEngineId=engine_id, policyId=out["policy_id"])
            out["delete_attempts"] = attempt
            if drec.ok:
                out["deleted"] = True
                out["delete_error"] = ""
                break
            out["delete_error"] = drec.error_code
            time.sleep(DELETE_SLEEP_S * attempt)
        if drec.ok:
            state.drop("policy", f"f4probe_{member}_{variant}_{rep}")
    else:
        out["deleted"] = None
    return out


def main(argv: list[str] | None = None) -> int:
    ap = P.parser(CASE, __doc__)
    ap.add_argument("--state", default=None)
    ap.add_argument("--evidence-root", default=None)
    args = ap.parse_args(argv)

    variants_dry = {k: v["tests"] for k, v in
                    statement_variants("arn:aws:bedrock-agentcore:us-east-1:0:gateway/dry").items()}
    if args.dry_run:
        # NOT P.dry_run_banner. That function's first act is `O.BINDINGS[case_id]`, and F4-0 has
        # no sealed binding — deliberately, because it has no oracle. The KeyError it raises is
        # the seal working: a script cannot print a pre-registered oracle it does not have. So
        # calibration prints its own banner, and the difference is visible to a reader.
        n_cells = len(DEFINITION_MEMBERS) * len(variants_dry)
        print(f"{CASE} dry run — no AWS call, no mutation\n")
        print("NO ORACLE, NO PRE-REGISTERED n, NO ALPHA, NO FAMILY.")
        print("This is instrument calibration: it decides which CreatePolicy request shape F4")
        print("must send, and writes the alternative-explanation register an F4 finding cites.")
        print("It publishes no claim about the document under test.\n")
        print(f"cells ({n_cells}, each sent {REPEATS}x under different names):")
        for m in DEFINITION_MEMBERS:
            for v, why in variants_dry.items():
                print(f"  definition.{m:<7} x {v:<13}  {why}")
        print(f"\ntotal calls: {n_cells * REPEATS} CreatePolicy + "
              f"<= {n_cells * REPEATS} DeletePolicy")
        print("billable text units: 0 — control plane only; no gateway request, no model, "
              "no guardrail evaluation")
        print("mutations: 0 — purely additive. No existing resource is modified: not the shared "
              "baseline permit, not either mode axis, not the engine")
        for line in (
            "each cell is sent twice under different names; disagreement makes the cell UNUSABLE "
            "rather than averaged, because a Cedar parse is deterministic and two different "
            "answers would mean the instrument, not the grammar, is the variable",
            "`no_condition` is the control column. If it fails for a member, that member is not "
            "a usable request shape and its guardrail cells carry no information about guardrail "
            "grammar",
            "the condition BODY is byte-identical between doc_syntax and plain_when, so the "
            "keyword is the only thing that differs between them",
            "plain_when is composed by hand rather than through cedar.statement(when=...), "
            "because lib/cedar.py raises on a guardrail function inside a standard `when` — that "
            "guard is an encoding of the document's L322 claim, which is one of the things in "
            "question here",
            "DeletePolicy runs for every accepted policy, in a finally, and the ledger entry is "
            "written BEFORE the delete: `policy` accepts no tags, so a kill between create and "
            "delete leaves state.json as the only channel that can find it",
            "$0, at most 28 CreatePolicy at the self-imposed 5/s limit",
            "teardown re-runs infra/06_verify.py's own verify_engine and verify_gateways anyway: "
            "'the probe changed nothing' is a claim, not an assumption",
        ):
            print(f"  - {line}")
        return 0

    try:
        state = T.State.load(Path(args.state) if args.state else None)
    except FileNotFoundError as exc:
        print(f"FATAL: {exc}", file=sys.stderr)
        return 2

    run_id = state.run_id
    admin = A.factory(args.region)
    ac = admin.agentcore_control()
    account_id = A.account_id(admin)
    store = EvidenceStore(run_id, FAMILY, CASE,
                          root=Path(args.evidence_root) if args.evidence_root else None)
    store.write_environment()

    gw = state.find("gateway", "main")
    eng = state.find("policy-engine", "main")
    if not (gw and eng):
        print("FATAL: the ledger has no main gateway or policy engine.", file=sys.stderr)
        return 2
    engine_id = eng.ids["policy_engine_id"]
    gateway_arn = T.unmask_arn(gw.arn, account_id)
    variants = statement_variants(gateway_arn)

    print(f"{CASE} — CreatePolicy request-shape calibration for guardrails-in-policy syntax")
    print(f"run_id={run_id} region={args.region} engine={engine_id}\n")

    rows: list[dict[str, Any]] = []
    try:
        for member in DEFINITION_MEMBERS:
            for variant, spec in variants.items():
                for rep in range(1, REPEATS + 1):
                    r = _probe(ac, store, state, engine_id=engine_id, member=member,
                               variant=variant, statement=spec["statement"], run_id=run_id,
                               rep=rep)
                    r["tests"] = spec["tests"]
                    rows.append(r)
                    mark = "ACCEPTED" if r["accepted"] else f"REJECTED {r['error_code']}"
                    print(f"  definition.{member:<7} x {variant:<13} rep{rep}  {mark}")
                    if not r["accepted"]:
                        print(f"      {(r['error_message'] or '')[:200]}")
                    time.sleep(0.2)
    finally:
        c = Checks()
        verify_engine(ac, state, c)
        verify_gateways(ac, state, account_id, args.region, c)
        print("\nblocking assertion, re-run after the probe:")
        c.print()

        leaked = [r for r in rows if r.get("policy_id") and not r.get("deleted")]
        cells: dict[str, dict[str, Any]] = {}
        for r in rows:
            key = f"{r['member']}.{r['variant']}"
            cells.setdefault(key, {"member": r["member"], "variant": r["variant"],
                                   "tests": r.get("tests", ""), "results": []})
            cells[key]["results"].append(
                {"rep": r["rep"], "accepted": r["accepted"], "error_code": r["error_code"],
                 "error_message": r["error_message"], "request_id": r["request_id"]})
        for key, cell in cells.items():
            acc = {x["accepted"] for x in cell["results"]}
            cell["stable"] = len(acc) == 1
            cell["accepted"] = next(iter(acc)) if cell["stable"] else None
            cell["usable"] = cell["stable"]

        control_ok = {m: cells.get(f"{m}.no_condition", {}).get("accepted")
                      for m in DEFINITION_MEMBERS}
        summary = {
            "case": CASE, "kind": "calibration", "run_id": run_id, "region": args.region,
            "sdk": A.sdk_versions(),
            "cells": cells,
            "control_column": control_ok,
            "leaked_policies": leaked,
            "verify": c.to_json(),
            "condition_body": COND,
            "hypotheses": {
                "H1": "the document is wrong about guardrails-in-policy syntax or availability",
                "H2": "the harness sent definition.cedar where definition.policy is required",
                "H3": "the keyword is right but lib/cedar.py's condition body is wrong",
                "H4": "the feature is not available on this engine/region/account",
            },
            "reading_rule": (
                "H2 is supported iff doc_syntax is REJECTED under cedar and ACCEPTED under "
                "policy, with policy's no_condition control ACCEPTED. H3 is supported iff both "
                "doc_syntax and plain_when are rejected with an error naming a token INSIDE the "
                "body rather than `guardrails`. H1 survives only if no member accepts the body "
                "in any form while that member's control is accepted — and even then it is a "
                "conflict candidate needing a second UTC day, not a finding"),
            "not_a_verdict": (
                "no oracle, no pre-registered n, no alpha, no family. This table decides which "
                "request shape F4 sends. It is cited by an F4 finding; it is not itself one"),
        }
        p = store.dir / "calibration.json"
        p.write_text(json.dumps(summary, indent=2, default=str))
        store.write_summary()
        print(f"\nwrote {p}")

        if leaked:
            print(f"\nFATAL: {len(leaked)} probe policy/policies could not be deleted. They are "
                  f"in state.json — the ONLY channel that can find them.", file=sys.stderr)
            for r in leaked:
                print(f"  - {r['name']} ({r['policy_id']}): {r.get('delete_error')}",
                      file=sys.stderr)
            return 2
        if not c.ok:
            print("\nFATAL: the testbed did not verify after a probe that was supposed to be "
                  "purely additive.", file=sys.stderr)
            return 2

    print("\nreading:")
    for key, cell in cells.items():
        state_txt = ("ACCEPTED" if cell["accepted"] else "REJECTED") if cell["stable"] \
            else "UNSTABLE (reps disagreed — cell unusable)"
        print(f"  {key:<22} {state_txt}")
    print(f"\ncontrol column (no_condition): {control_ok}")
    print("\nThis is calibration. No claim about the document is published from this file; "
          "O.not_measured is not emitted either, because F4-0 is not a pre-registered case.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
